<a href="https://colab.research.google.com/github/riquessl/pfg/blob/main/Acid_Hydrolysis_Model_Optimization_PFG_Henrique_Lima.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

The following model for the concentration of glucose via the acid hydrolysis of bleached kraft pulp was obtained on a paper written by Wang, Zhao and Zhu in 2014.

$$ C_{glu} = \frac{1.111 \cdot C_{cel,0} \cdot \gamma \cdot (k_3 - k_2)}{(k_1 + k_3 - k_2)} \cdot \{1 - exp [-(k_1 - k_3) \cdot t]\} + \frac{1.111 \cdot C_{cel,0} \cdot \gamma \cdot k_1}{(k_1 + k_3 - k_2)} \cdot [1 - exp(-k_2 \cdot t)] \tag{8c} $$

In which:

- $C_{glu}$ is the concentration of glucose after the acid hydrolysis;  
- $C_{cel,0}$ is the initial concentration of cellulose  
- $\gamma$ is the "degree of hydrolysis", the fraction of cellulose thea was depolymerized to the form of glucose;  
- $k_1$ is the rate constat that represents the reaction from noncrystalline cellulose hydrolysed to cellulose nanocrystals (CNCs);  
- $k_2$ is the rate constat that represents the reaction from CNCs hydrolysed to glucose under severe conditions;  
- $k_3$is the rate constat that represents the reaction from noncrystalline cellulose directly hydrolysed to glucose;  
- $t$ is the hydrolysis time.

The full paper can be read by clicking the link bellow:

https://www.fpl.fs.usda.gov/documnts/pdf2014/fpl_2014_wang002.pdf

Some supporting information can be found on the following link:  

https://pubs.acs.org/doi/suppl/10.1021/ie501672m/suppl_file/ie501672m_si_001.pdf

### Cellulose concentration

The concentration of cellulose measured in the pulp was 78.1 $\pm$ 1.0%. However the normalized value of 84.4% was used in the paper because some of the components were undetectable.

### Acid Hydrolysis experiments

- Range of acid concentration: 50 - 64% m/m
- Temperature range: 35 - 80 °C
- Reaction times range: 15 - 240 min

### Kinetic constants

Using equations $18a$ and $18b$, its possible to calculate $k_1$ and $k_3$ according to the acid concentration and the temperature.

$$ k_1 = 4.8059 \cdot exp \Bigg (- \frac{36353}{R \cdot T} \Bigg ) \cdot C_{SA}^{3.8157} \tag{18a} $$  

$$ k_3 = 24.1186 \cdot exp \Bigg (- \frac{40222}{R \cdot T} \Bigg ) \cdot C_{SA}^{3.2566} \tag{18b} $$  

In which:

- $R$ is the combined severity factor
- $C_{SA}$ is the acid concentration
- $T$ is the temperature in K

### Severity Factor ($R_0$) and Combined Severity Factor ($R$)

$$ R_0 = exp \Bigg ( \frac{T' - T_r}{14.75}\Bigg ) \tag{19}$$  

$$ R = C_{SA}^n \cdot R_0 \tag{20} $$

In which:

- $T'$ is the temperature in Celsius  
- $T_r$ is the reference temperature (25 °C)
- $n$ is the strong acid dependence of the hydrolysis reaction

### Degree of hydrolysis

$$ \gamma = 1 - \frac{60.8259}{C_{SA}^{1.9752} \cdot R_0^{0.1314}} \tag {23a} $$

### Data

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
C_SA_mol_L = [7.097,7.097,7.097,7.097,8.295,8.295,8.295,8.295,8.715,9.589,9.589,9.589,9.589,10.043]
C_SA_mm    = [50.00,50.00,50.00,50.00,56.00,56.00,56.00,56.00,58.00,62.00,62.00,62.00,62.00, 64.00]
T_oC       = [50.00,60.00,70.00,80.00,40.00,50.00,60.00,70.00,56.00,35.00,40.00,50.00,60.00, 45.00]
t_opt_min  = [239.0,229.0,294.0, 82.0,291.0,202.0,143.0,103.0,205.0,228.0,195.0,101.0, 30.0,  64.0]
t_exp_min  = [240.0,240.0,240.0, 90.0,240.0,210.0,150.0, 90.0,210.0,180.0,120.0, 75.0, 60.0,  15.0]
C_glu_g_L  = [ 2.00, 5.10, 5.40, 5.70, 1.40, 6.50, 7.70,12.20, 7.50,32.60,19.30,22.00,21.70, 32.00]

In [ ]:
T_K = [x + 273.15 for x in T_oC]
T_K

[323.15,
 333.15,
 343.15,
 353.15,
 313.15,
 323.15,
 333.15,
 343.15,
 329.15,
 308.15,
 313.15,
 323.15,
 333.15,
 318.15]

In [ ]:
data = pd.DataFrame(C_SA_mol_L,columns=['C_SA_mol_L'])

In [ ]:
data['C_SA_mm']   = C_SA_mm
data['T_oC']      = T_oC
data['T_K']       = T_K
data['t_opt_min'] = t_opt_min
data['t_exp_min'] = t_exp_min
data['C_glu_g_L'] = C_glu_g_L

In [ ]:
data

    C_SA_mol_L  C_SA_mm  T_oC     T_K  t_opt_min  t_exp_min  C_glu_g_L
0        7.097     50.0  50.0  323.15      239.0      240.0        2.0
1        7.097     50.0  60.0  333.15      229.0      240.0        5.1
2        7.097     50.0  70.0  343.15      294.0      240.0        5.4
3        7.097     50.0  80.0  353.15       82.0       90.0        5.7
4        8.295     56.0  40.0  313.15      291.0      240.0        1.4
5        8.295     56.0  50.0  323.15      202.0      210.0        6.5
6        8.295     56.0  60.0  333.15      143.0      150.0        7.7
7        8.295     56.0  70.0  343.15      103.0       90.0       12.2
8        8.715     58.0  56.0  329.15      205.0      210.0        7.5
9        9.589     62.0  35.0  308.15      228.0      180.0       32.6
10       9.589     62.0  40.0  313.15      195.0      120.0       19.3
11       9.589     62.0  50.0  323.15      101.0       75.0       22.0
12       9.589     62.0  60.0  333.15       30.0       60.0       21.7
13      10.043     64.0  45.0  318.15       64.0       15.0       32.0

#### Adding the data from the supporting information

In [ ]:
gamma = [0.0525,0.0957, 0.1439,0.1538,0.1619,0.2216,0.2620,0.4628,0.9993,1.0000,1.0000,1.0000,1.0000,1.0000]
k_1   = [0.0428,0.0134, 0.0228,0.0375,0.0205,0.0093,0.0167,0.0358,0.0312,0.0080,0.0144,0.0470,0.1660,0.0972]
k_2   = [0.0004,0.0001,0.00001,0.0008,0.0001,0.0001,0.0001,0.0001,0.0001,0.0001,0.0008,0.0002,0.0005,0.0031]
k_3   = [0.0079,0.0115, 0.0131,0.0143,0.0061,0.0043,0.0064,0.0094,0.0089,0.0026,0.0018,0.0092,0.0342,0.0110]
data['gamma'] = gamma
data['k1_1smin'] = k_1
data['k2_1smin'] = k_2
data['k3_1smin'] = k_3
data

,C_SA_mol_L,C_SA_mm,T_oC,T_K,t_opt_min,t_exp_min,C_glu_g_L,gamma,k1_1smin,k2_1smin,k3_1smin
0,7.097,50.0,50.0,323.15,239.0,240.0,2.0,0.0525,0.0428,0.00040,0.0079
1,7.097,50.0,60.0,333.15,229.0,240.0,5.1,0.0957,0.0134,0.00010,0.0115
2,7.097,50.0,70.0,343.15,294.0,240.0,5.4,0.1439,0.0228,0.00001,0.0131
3,7.097,50.0,80.0,353.15,82.0,90.0,5.7,0.1538,0.0375,0.00080,0.0143
4,8.295,56.0,40.0,313.15,291.0,240.0,1.4,0.1619,0.0205,0.00010,0.0061
5,8.295,56.0,50.0,323.15,202.0,210.0,6.5,0.2216,0.0093,0.00010,0.0043
6,8.295,56.0,60.0,333.15,143.0,150.0,7.7,0.2620,0.0167,0.00010,0.0064
7,8.295,56.0,70.0,343.15,103.0,90.0,12.2,0.4628,0.0358,0.00010,0.0094
8,8.715,58.0,56.0,329.15,205.0,210.0,7.5,0.9993,0.0312,0.00010,0.0089
9,9.589,62.0,35.0,308.15,228.0,180.0,32.6,1.0000,0.0080,0.00010,0.0026
10,9.589,62.0,40.0,313.15,195.0,120.0,19.3,1.0000,0.0144,0.00080,0.0018
11,9.589,62.0,50.0,323.15,101.0,75.0,22.0,1.0000,0.0470,0.00020,0.0092
12,9.589,62.0,60.0,333.15,30.0,60.0,21.7,1.0000,0.1660,0.00050,0.0342
13,10.043,64.0,45.0,318.15,64.0,15.0,32.0,1.0000,0.0972,0.00310,0.0110

In [ ]:
zeros         = np.zeros(shape=len(data['T_K']))
C_cel_0_g_L   = [x+42.2 for x in zeros]
C_cel_0_mol_L = [x/162.14 for x in C_cel_0_g_L]
data['C_cel_0_g_L']   = C_cel_0_g_L
data['C_cel_0_mol_L'] = C_cel_0_mol_L
data.head()

,C_SA_mol_L,C_SA_mm,T_oC,T_K,t_opt_min,t_exp_min,C_glu_g_L,gamma,k1_1smin,k2_1smin,k3_1smin,C_cel_0_g_L,C_cel_0_mol_L
0,7.097,50.0,50.0,323.15,239.0,240.0,2.0,0.0525,0.0428,0.00040,0.0079,42.2,0.260269
1,7.097,50.0,60.0,333.15,229.0,240.0,5.1,0.0957,0.0134,0.00010,0.0115,42.2,0.260269
2,7.097,50.0,70.0,343.15,294.0,240.0,5.4,0.1439,0.0228,0.00001,0.0131,42.2,0.260269
3,7.097,50.0,80.0,353.15,82.0,90.0,5.7,0.1538,0.0375,0.00080,0.0143,42.2,0.260269
4,8.295,56.0,40.0,313.15,291.0,240.0,1.4,0.1619,0.0205,0.00010,0.0061,42.2,0.260269

### Defining the equation to glucose (Eq. 8c)

In [ ]:
def Eq_8c(gamma,k_1,k_2,k_3,C_cel_0,t):
  fac1a = 1.111 * C_cel_0 * gamma * (k_3 - k_2) / (k_1 + k_3 - k_2)
  fac_1 = fac1a * (1 - np.exp(-(k_1 - k_3) * t))
  fac2a = (1.111 * C_cel_0 * gamma * k_1) / (k_1 + k_3 - k_2)
  fac_2 = fac2a * (1 - np.exp(-k_2 * t))
  C_glu = fac_1 + fac_2
  return C_glu

In [ ]:
data.at[0,'gamma']

0.0525

In [ ]:
C_glu_Eq = Eq_8c(data['gamma'],data['k1_1smin'],data['k2_1smin'],
                 data['k3_1smin'],data['C_cel_0_g_L'],data['t_exp_min'])
C_glu_Eq

0      0.558640
1      0.812746
2      2.231053
3      2.040508
4      1.803632
5      2.249932
6      2.779721
7      4.212870
8     10.971372
9      7.576923
10     6.386144
11     7.678353
12     9.060752
13     4.527024
dtype: float64

In [ ]:
comp = pd.DataFrame(C_glu_g_L,columns=['C_glu_paper'])
comp['C_glu_Eq'] = C_glu_Eq
comp.head()

   C_glu_paper  C_glu_Eq
0          2.0  0.558640
1          5.1  0.812746
2          5.4  2.231053
3          5.7  2.040508
4          1.4  1.803632

In [ ]:
error = ((comp['C_glu_Eq'] - comp['C_glu_paper'])/comp['C_glu_paper'])**2
error

0     0.519379
1     0.706672
2     0.344384
3     0.412185
4     0.083122
5     0.427529
6     0.408318
7     0.428610
8     0.214230
9     0.589178
10    0.447710
11    0.423780
12    0.339252
13    0.737075
dtype: float64